### ISSUE TITLE
Update Mint

### ISSUE THREAD

**Issue by saneery** [funbox/kashka#5]
`Kashka` has errors with new version of Elixir, the cause in old version of Mint

```
Interactive Elixir (1.12.3) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Mint.HTTP.connect(:https, "https://www.yandex.ru", 443, [transport_opts: [verify: :verify_none]])                                                                                                   ** (UndefinedFunctionError) function :ssl.cipher_suites/0 is undefined or private, use cipher_suites/2,3 instead
    (ssl 10.5) :ssl.cipher_suites()
    (mint 0.4.0) lib/mint/core/transport/ssl.ex:558: Mint.Core.Transport.SSL.default_ciphers/0
    (mint 0.4.0) lib/mint/core/transport/ssl.ex:474: Mint.Core.Transport.SSL.default_ssl_opts/1
    (mint 0.4.0) lib/mint/core/transport/ssl.ex:405: Mint.Core.Transport.SSL.ssl_opts/2
    (mint 0.4.0) lib/mint/core/transport/ssl.ex:318: Mint.Core.Transport.SSL.connect/3
    (mint 0.4.0) lib/mint/negotiate.ex:65: Mint.Negotiate.connect_negotiate/4
```

`ssl:cipher_suites/0` deprecated in OTP 21

**Comment by saneery** [comment]
https://github.com/funbox/kashka/pull/6
